name: 🐞 Bug Report
description: File a bug report
title: "🐞 Bug: "
labels: [🐞 bug]
body:
  - type: textarea
    attributes:
      label: Detailed Bug Description
      description: Provide a detailed explanation of the bug. Include the steps to reproduce it, your expected outcome, and the actual outcome. A thorough description will help us resolve the issue more efficiently.
      placeholder: "Steps to reproduce the bug...\n\nExpected outcome...\n\nActual outcome..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant Log Output
      description: >
        Paste any relevant log output here (e.g., Xcode logs, Android Studio Logcat).
        This will be formatted as code automatically.

        * For iOS: Run the project in Xcode and copy the logs from the log window.
        * For Android: Use Android Studio's Logcat window or run `adb logcat` in the terminal.
      render: shell
      placeholder: "Paste log output here..."
    validations:
      required: false
  - type: input
    attributes:
      label: Device Information
      description: Provide details about the device(s) where you encountered this issue. Include the full device name, operating system, and version. If applicable, mention all devices tested.
      placeholder: "e.g., iPhone 11 Pro (iOS 14.3), Samsung Galaxy S21 (Android 11)"
    validations:
      required: true
  - type: input
    attributes:
      label: Reproducible Code Link
      description: Provide a link to a repository or Snack that reproduces the issue.
      placeholder: "Paste URL here..."
    validations:
      required: false
  - type: input
    attributes:
      label: react-native-vision-camera-mlkit Version
      description: Specify the version of react-native-vision-camera-mlkit you are using.
      placeholder: "e.g., 1.0.0"
    validations:
      required: true
  - type: input
    attributes:
      label: react-native-vision-camera Version
      description: Specify the version of react-native-vision-camera you are using.
      placeholder: "e.g., 4.0.0"
    validations:
      required: true
  - type: input
    attributes:
      label: react-native-worklets-core Version
      description: Specify the version of react-native-worklets-core you are using.
      placeholder: "e.g., 1.3.0"
    validations:
      required: true
