name: 🔧 Build Error
description: File a build error bug report
title: "🔧 Build error: "
labels: [🔧 build error]
body:
  - type: textarea
    attributes:
      label: Build Method
      description: Describe how you attempted to build the app. Specify if you used Xcode, `yarn ios`, a CI system, or another method.
      placeholder: "e.g., I tried to build my app with the `yarn ios` command, and it failed."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Complete Build Logs
      description: Provide the complete build logs from the console. Ensure you include everything from start to end, not just the last few lines.
      render: shell
      placeholder: "Paste full build log output here..."
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Target Platforms
      description: Select the platforms where the build error occurs.
      multiple: true
      options:
        - iOS
        - Android
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Operating System
      description: Select the operating system on which you are trying to build.
      multiple: true
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true
  - type: input
    attributes:
      label: react-native-vision-camera-mlkit Version
      description: Specify the version of react-native-vision-camera-mlkit you are using.
      placeholder: "e.g., 1.0.0"
    validations:
      required: true
  - type: input
    attributes:
      label: react-native-vision-camera Version
      description: Specify the version of react-native-vision-camera you are using.
      placeholder: "e.g., 4.0.0"
    validations:
      required: true
  - type: input
    attributes:
      label: react-native-worklets-core Version
      description: Specify the version of react-native-worklets-core you are using.
      placeholder: "e.g., 1.3.0"
    validations:
      required: true
