name: Mark stale issues and pull requests
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 90
          stale-issue-message: 'This issue is stale because it has been open 90 days with no activity. Please comment or this will be closed in 7 days.'
          stale-pr-message: 'This PR is stale because it has been open 90 days with no activity. Please comment or this will be closed in 7 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stalled for 7 days with no activity.'
          stale-issue-label: ⏳ stale
          stale-pr-label: ⏳ stale
          exempt-issue-labels: 📢 help wanted, 💭 question, ☠️ wontfix
          exempt-pr-labels: 📢 help wanted, 💭 question, ☠️ wontfix
          exempt-all-milestones: true
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 30
          stale-issue-message: 'This issue is waiting for authors feedback since 30 days. Please comment providing the requested feedback or this issue will be closed in 7 days.'
          stale-pr-message: 'This PR is waiting for authors feedback since 30 days. Please comment providing the requested feedback or this PR will be closed in 7 days.'
          close-issue-message: 'This issue was closed because its author has not followed up after 7 days.'
          close-pr-message: 'This PR was closed because its author has not followed up after 7 days.'
          stale-issue-label: ⏳ stale
          stale-pr-label: ⏳ stale
          exempt-issue-labels: 📢 help wanted, 💭 question, ☠️ wontfix
          exempt-pr-labels: 📢 help wanted, 💭 question, ☠️ wontfix
          exempt-all-milestones: true
